### ISSUE TITLE
Compiling with arm-eabi

### ISSUE THREAD

**Issue by LabNelson** [TImada/raspi4_freertos#6]
I want to add this port to an application with a large code base.
The code base is compiled on windows with msys and arm-eabi-toolchain (gcc-linaro-6.2.1-20170623-win32). I got the compiler on my computer but its too large to share via github-repository.
Does anyone tried to compile this port with arm-eabi, another toolchain or can point me in the right direction?
When compiling with arm-eabi 
``arm-eabi-as -mcpu=cortex-a72 -c -o build/startup.o src/startup.S``

i got the following errors:
``` makefile
src/startup.S: Assembler messages:
src/startup.S:9: Error: ARM register expected -- 'mrs x1,mpidr_el1'
src/startup.S:10: Error: ARM register expected -- 'and x1,x1,#3'
src/startup.S:11: Error: ARM register expected -- 'cmp x1,#3'
src/startup.S:16: Error: ARM register expected -- 'mov x0,#(1<<31)'
src/startup.S:17: Error: ARM register expected -- 'orr x0,x0,#(1<<1)'
src/startup.S:18: Error: selected processor does not support requested special purpose register -- 'msr hcr_el2,x0'
src/startup.S:21: Error: ARM register expected -- 'mov x2,#0x3c5'
src/startup.S:22: Error: flag for {c}psr instruction expected -- 'msr spsr_el2,x2'
src/startup.S:24: Error: ARM register expected -- 'adr x2,start_el1'
src/startup.S:25: Error: selected processor does not support requested special purpose register -- 'msr elr_el2,x2'
src/startup.S:31: Error: ARM register expected -- 'mrs x1,cpacr_el1'
src/startup.S:32: Error: ARM register expected -- 'mov x0,#(3<<20)'
src/startup.S:33: Error: ARM register expected -- 'orr x0,x1,x0'
src/startup.S:34: Error: selected processor does not support requested special purpose register -- 'msr cpacr_el1,x0'
src/startup.S:36: Error: bad instruction 'adrp x1,stack_top'
src/startup.S:37: Error: immediate expression requires a # prefix -- 'mov sp,x1'
src/startup.S:39: Error: ARM register expected -- 'ldr x0,=configure_mmu'
src/startup.S:40: Error: bad instruction 'blr x0'
src/startup.S:42: Error: ARM register expected -- 'ldr x1,=__bss_start'
src/startup.S:43: Error: ARM register expected --'ldr w2,=__bss_size'
src/startup.S:44: Error: selected processor does not support 'cbz w2,2f' in ARM mode
src/startup.S:45: Error: ARM register expected -- 'str xzr,[x1],#8'
src/startup.S:46: Error: ARM register expected -- 'sub w2,w2,#1'
src/startup.S:47: Error: selected processor does not support 'cbnz w2,1b' in ARM mode
src/startup.S:50: Error: bad instruction 'ret'
src/startup.S:53: Error: ARM register expected -- 'mov x1,#0xF0'
src/startup.S:54: Error: ARM register expected -- 'ldr x2,=__start'
src/startup.S:55: Error: ARM register expected -- 'str x2,[x1]'
src/startup.S:58: Error: ARM register expected -- 'mov x0,#0x0'
src/startup.S:59: Error: bad instruction 'ret'
make: *** [Makefile:75: build/startup.o] Error 1### ### 
```

**Comment by LabNelson** [comment]
Looks like the port uses 64-bit instructions and i try compile it with 32-bit compiler.
Can i just change the arm-eabi 32-bit compiler to 64-bit without problems?

**Comment by TImada** [comment]
> Can i just change the arm-eabi 32-bit compiler to 64-bit without problems?

aarch64-none-elf should work. (but I'm not sure if or not the latest GCC version can work correctly)

> I will try [mingw-w64-i686-arm-none-eabi-toolchain](https://developer.arm.com/-/media/Files/downloads/gnu/13.2.rel1/binrel/arm-gnu-toolchain-13.2.rel1-mingw-w64-i686-arm-none-eabi.zip?rev=93fda279901c4c0299e03e5c4899b51f&hash=99EF910A1409E119125AF8FED325CF79)

That's arm-none-eabi, not aarch64-none-elf.

**Comment by LabNelson** [comment]
> >    Can i just change the arm-eabi 32-bit compiler to 64-bit without problems?
>aarch64-none-elf should work. (but I'm not sure if or not the latest GCC version can work correctly)
Do you mean that aarch64-none-elf should work for the code base which is compiled by arm-eabi-toolchain (gcc-linaro-6.2.1-20170623-win32)?
So i need an aarch64-none-elf compiler which has the same version of GCC (probably from 2017)?

**Comment by TImada** [comment]
> Do you mean that aarch64-none-elf should work for the code base which is compiled by arm-eabi-toolchain (gcc-linaro-6.2.1-20170623-win32)?

What I mean is just that a GCC compiler toolchain marked as 'aarch64-none-elf' (e.g. obtained from [1]) should work for compiling this UART sample.

[1] https://developer.arm.com/downloads/-/gnu-a

> I dont find the xil_smc.h in any project folder, so it must be located in the libxil.a or in an installation-directory of arm-eabi-toolchain?

I'm not sure why your toolchain environment tries to access Xilinx related files like libxil.a or xil_smc.h. You should check your build configuration.

**Comment by LabNelson** [comment]
> What I mean is just that a GCC compiler toolchain marked as 'aarch64-none-elf' (e.g. obtained from [1]) should work for compiling this UART sample.

That's working fine for the UART-sample. I want to compile my large code base and the UART-sample with one compiler.
aarch64-none-elf sadly doesn't work for the code base (due to this error). And arm-eabi does'nt work for the FreeRTOS-port (due to missing 64-bit instructions).

The code base is based on the Xlinx Zynq board (where FreeRTOS is also ported for). My aim is to change this port so the RPi4 is working with FreeRTOS and the large code base (maybe xil_smc.h is used in a driver). Your port serves me the FreeRTOS-part, so now I will tackle the other driver related stuff.
Yes, I will check, what exactly is hidden in the libxil.a or in the xil_smc.h files. Probably I don't need them.
Thank you so far, for your help @TImada - I will keep this thread updated

**Comment by TImada** [comment]
> I will keep this thread updated

Close this issue as the it has nothing with your build environment for the code base any more.

**Comment by LabNelson** [comment]
I changed the compiler to [gcc-arm-8.2-2018.08-i686-mingw32-aarch64-elf.tar.xz](https://developer.arm.com/-/media/Files/downloads/gnu-a/8.2-2018.08/gcc-arm-8.2-2018.08-i686-mingw32-aarch64-elf.tar.xz?revision=6aca29f5-5d11-4e0b-a3b2-83afc5da5ad2&ln=en&hash=C31784A539931F3A9976E6317C255E48).
It works for your port, but i have to convert the large codebase from 32-bit to 64-bit, yay
